added Bash 'Strict Mode': enabled pipefail opt - signed-off-by: trimstray <contact@nslab.at>

diff --git a/dracnmap b/dracnmap
--- a/dracnmap
+++ b/dracnmap
@@ -17,6 +17,19 @@
 ############################# Prepare environment ##############################
 ################################################################################
 
+# Bash 'Strict Mode':
+#   errexit  - exit the script if any statement returns a non-true return value
+#   pipefail - exit the script if any command in a pipeline errors
+#   nounset  - exit the script if you try to use an uninitialised variable
+#   xtrace   - display debugging information
+set -o pipefail
+
+# Setting permissions in the script environment:
+#   0022 - less restrictive settings (default value)
+#   0027 - for better security than above
+#   0077 - only for user access (more restrictive)
+umask 0027
+
 if [[ $EUID -ne 0 ]] ; then
 
   echo -en "ERROR! Run this script with root user.\n"
@@ -34,12 +47,6 @@ else
   resize -s 50 89 > /dev/null
 
 fi
-
-# Setting permissions in the script environment:
-#   0022 - less restrictive settings (default value)
-#   0027 - for better security than above
-#   0077 - only for user access (more restrictive)
-umask 0027
 
 
 ################################################################################
