_init_cmd(): minor fixes and updated output - signed-off-by: trimstray <contact@nslab.at>

diff --git a/src/functions b/src/functions
--- a/src/functions
+++ b/src/functions
@@ -789,24 +789,27 @@ function _init_cmd() {
 
   if [[ -z "$_output_path" ]] ; then
 
-    printf "\nNmap args:\n> \e[0;30m%s\e[m\n" "${_cmd[@]}"
+    printf "\n\e[1;39m%s\e[m:\n> \e[0;30m%s\e[m\n" "Full command" "nmap ${_cmd[@]}"
+
+    # Execute command and exit.
+    nmap ${_cmd[@]} ; _state="$?"
 
   else
 
-    printf "\nNmap args:\n> \e[0;30m%s\e[m\n> \e[0;30m%s\e[m\n" "${_cmd[@]}" "$_output_path"
+    printf "\n\e[1;39m%s\e[m:\n>\e[0;30m%s\e[m\n> \e[0;30m%s\e[m\n" "Full command" "nmap ${_cmd[@]}" "$_output_path"
+
+    # Execute command and exit.
+    nmap ${_cmd[@]} "${_output_targ}" ; _state="$?"
 
   fi
 
-  # Execute command and exit.
-  nmap ${_cmd[@]} "${_output_targ}" ; _state="$?"
-
   if [[ "$_state" -eq 0 ]] ; then
 
-    printf "\nResult: \e[0;32m%s\e[m\n\n" "pass"
+    printf "\n\e[1;39m%s\e[m: \e[0;32m%s\e[m\n\n" "Result" "pass"
 
   else
 
-    printf "\nResult: \e[0;31m%s\e[m\n\n" "fail"
+    printf "\n\e[1;39m%s\e[m: \e[0;31m%s\e[m\n\n" "Result" "fail"
 
   fi
 
